FROM ${REGISTRY}/it/node:16-alpine
RUN apk update && apk add --no-cache make bash
WORKDIR /app
COPY package.json package.json
COPY package-lock.json package-lock.json

COPY tsconfig.json tsconfig.json
COPY .eslintignore .eslintignore
COPY .eslintrc.js .eslintrc.js
COPY packages packages
COPY example example
COPY lerna.json lerna.json
RUN npm ci -q
CMD npm run test-ci
